// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Api.Infrastructure;

#nullable disable

namespace Api.Migrations.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260208073313_RemoveExtractedPath")]
    partial class RemoveExtractedPath
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Api.Domain.Entities.ApiKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AppId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<string>("Metadata")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.ToTable("ApiKeys");
                });

            modelBuilder.Entity("Api.Domain.Entities.ApiToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HashedToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ApiTokens");
                });

            modelBuilder.Entity("Api.Domain.Entities.App", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("ActiveReleaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("OwnerId")
                        .HasColumnType("text");

                    b.Property<string>("RoutingConfig")
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ActiveReleaseId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Apps");
                });

            modelBuilder.Entity("Api.Domain.Entities.AppBuild", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AppId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.ToTable("AppBuildJobs");
                });

            modelBuilder.Entity("Api.Domain.Entities.AppBuildArtifact", b =>
                {
                    b.Property<Guid>("BuildJobId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArtifactId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("BuildJobId", "ArtifactId");

                    b.HasIndex("ArtifactId");

                    b.ToTable("AppBuildArtifacts");
                });

            modelBuilder.Entity("Api.Domain.Entities.AppLink", b =>
                {
                    b.Property<int>("AppId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("InstallationId")
                        .HasColumnType("bigint");

                    b.Property<long>("RepoId")
                        .HasColumnType("bigint");

                    b.Property<string>("RepoName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("AppId");

                    b.HasIndex("InstallationId");

                    b.ToTable("AppLink");
                });

            modelBuilder.Entity("Api.Domain.Entities.Artifact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AppId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("BuildId")
                        .HasColumnType("uuid");

                    b.Property<string>("BundleHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("BundleSize")
                        .HasColumnType("bigint");

                    b.Property<string>("Compression")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StorageKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("StorageType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.HasIndex("BuildId");

                    b.HasIndex("BundleHash")
                        .IsUnique();

                    b.ToTable("Artifacts");
                });

            modelBuilder.Entity("Api.Domain.Entities.AuthenticationScheme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AppId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("OpenIdConnectAudience")
                        .HasColumnType("text");

                    b.Property<string>("OpenIdConnectAuthority")
                        .HasColumnType("text");

                    b.Property<int?>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.ToTable("AuthenticationSchemes");
                });

            modelBuilder.Entity("Api.Domain.Entities.DeploymentFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BlobId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeploymentId")
                        .HasColumnType("uuid");

                    b.Property<string>("ETag")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Path")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BlobId");

                    b.HasIndex("DeploymentId");

                    b.HasIndex("DeploymentId", "Path")
                        .IsUnique();

                    b.ToTable("DeploymentFiles");
                });

            modelBuilder.Entity("Api.Domain.Entities.GitHubInstallation", b =>
                {
                    b.Property<long>("InstallationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("InstallationId"));

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<string>("AccountLogin")
                        .HasColumnType("text");

                    b.Property<int>("AccountType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("InstallationId");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("GitHubInstallations");
                });

            modelBuilder.Entity("Api.Domain.Entities.Log", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AppId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan?>("FunctionExecutionDuration")
                        .HasColumnType("interval");

                    b.Property<int?>("FunctionRuntime")
                        .HasColumnType("integer");

                    b.Property<string>("Method")
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .HasColumnType("text");

                    b.Property<string>("RemoteAddress")
                        .HasColumnType("text");

                    b.Property<long?>("RequestContentLength")
                        .HasColumnType("bigint");

                    b.Property<string>("RequestContentType")
                        .HasColumnType("text");

                    b.Property<string>("RequestCookie")
                        .HasColumnType("text");

                    b.Property<string>("RequestFormContent")
                        .HasColumnType("text");

                    b.Property<string>("RequestHeaders")
                        .HasColumnType("text");

                    b.Property<int?>("RouteId")
                        .HasColumnType("integer");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.HasIndex("RouteId");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("Api.Domain.Entities.ObjectBlob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ContentType")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("StorageType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash")
                        .IsUnique();

                    b.ToTable("ObjectBlobs");
                });

            modelBuilder.Entity("Api.Domain.Entities.Release", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AppId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SpaDeploymentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.HasIndex("SpaDeploymentId");

                    b.ToTable("Releases");
                });

            modelBuilder.Entity("Api.Domain.Entities.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AppId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int?>("FolderId")
                        .HasColumnType("integer");

                    b.Property<string[]>("FunctionHandlerDependencies")
                        .HasColumnType("text[]");

                    b.Property<string>("FunctionHandlerMethod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("handler");

                    b.Property<int?>("FunctionRuntime")
                        .HasColumnType("integer");

                    b.Property<string>("Method")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .HasColumnType("text");

                    b.Property<string>("RequestBodySchema")
                        .HasColumnType("text");

                    b.Property<string>("RequestHeaderSchema")
                        .HasColumnType("text");

                    b.Property<string>("RequestQuerySchema")
                        .HasColumnType("text");

                    b.Property<bool>("RequireAuthorization")
                        .HasColumnType("boolean");

                    b.Property<string>("Response")
                        .HasColumnType("text");

                    b.Property<string>("ResponseBodyLanguage")
                        .HasColumnType("text");

                    b.Property<int?>("ResponseStatusCode")
                        .HasColumnType("integer");

                    b.Property<int>("ResponseType")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.HasIndex("FolderId");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("Api.Domain.Entities.RouteFolder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AppId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.HasIndex("ParentId");

                    b.ToTable("RouteFolders");
                });

            modelBuilder.Entity("Api.Domain.Entities.SlackAppSubscription", b =>
                {
                    b.Property<string>("TeamId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ChannelId")
                        .HasColumnType("text");

                    b.Property<int?>("AppId")
                        .HasColumnType("integer");

                    b.Property<string>("SlackUserId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("integer");

                    b.HasKey("TeamId", "ChannelId", "AppId");

                    b.ToTable("SlackAppSubscriptions");
                });

            modelBuilder.Entity("Api.Domain.Entities.SlackInstallation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BotAccessToken")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("BotUserId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("EnterpriseId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("InstalledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InstalledByUserId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("IsEnterpriseInstall")
                        .HasColumnType("boolean");

                    b.Property<string>("Scopes")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("TeamId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TeamName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TeamId")
                        .IsUnique();

                    b.ToTable("SlackInstallations");
                });

            modelBuilder.Entity("Api.Domain.Entities.SlackUserLink", b =>
                {
                    b.Property<string>("TeamId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SlackUserId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("LinkedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("TeamId", "SlackUserId");

                    b.ToTable("SlackUserLinks");
                });

            modelBuilder.Entity("Api.Domain.Entities.SpaDeployment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AppId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ArtifactId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BuildId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ArtifactId");

                    b.HasIndex("BuildId");

                    b.HasIndex("AppId", "Status");

                    b.ToTable("SpaDeployments");
                });

            modelBuilder.Entity("Api.Domain.Entities.Variable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AppId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsSecret")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Target")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.ToTable("Variables");
                });

            modelBuilder.Entity("Api.Domain.Entities.ApiKey", b =>
                {
                    b.HasOne("Api.Domain.Entities.App", "App")
                        .WithMany("ApiKeys")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("App");
                });

            modelBuilder.Entity("Api.Domain.Entities.App", b =>
                {
                    b.HasOne("Api.Domain.Entities.Release", "ActiveRelease")
                        .WithMany()
                        .HasForeignKey("ActiveReleaseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("Api.Domain.Entities.AppBuildConfigs", "BuildConfigs", b1 =>
                        {
                            b1.Property<int>("AppId")
                                .HasColumnType("integer");

                            b1.Property<string>("Branch")
                                .HasColumnType("text");

                            b1.Property<string>("BuildCommand")
                                .HasColumnType("text");

                            b1.Property<string>("Directory")
                                .HasColumnType("text");

                            b1.Property<string>("Framework")
                                .HasColumnType("text");

                            b1.Property<string>("InstallCommand")
                                .HasColumnType("text");

                            b1.Property<string>("NodeVersion")
                                .HasColumnType("text");

                            b1.Property<string>("OutDir")
                                .HasColumnType("text");

                            b1.HasKey("AppId");

                            b1.ToTable("Apps");

                            b1.ToJson("BuildConfigs");

                            b1.WithOwner()
                                .HasForeignKey("AppId");
                        });

                    b.OwnsOne("Api.Domain.Entities.AppSettings", "Settings", b1 =>
                        {
                            b1.Property<int>("AppId")
                                .HasColumnType("integer");

                            b1.Property<bool>("CheckFunctionExecutionLimitMemory")
                                .HasColumnType("boolean");

                            b1.Property<bool>("CheckFunctionExecutionTimeout")
                                .HasColumnType("boolean");

                            b1.Property<long?>("FunctionExecutionLimitMemoryBytes")
                                .HasColumnType("bigint");

                            b1.Property<int?>("FunctionExecutionTimeoutSeconds")
                                .HasColumnType("integer");

                            b1.Property<bool>("FunctionUseNoSqlConnection")
                                .HasColumnType("boolean");

                            b1.HasKey("AppId");

                            b1.ToTable("Apps");

                            b1.ToJson("Settings");

                            b1.WithOwner()
                                .HasForeignKey("AppId");
                        });

                    b.OwnsOne("Api.Domain.Entities.CorsSettings", "CorsSettings", b1 =>
                        {
                            b1.Property<int>("AppId")
                                .HasColumnType("integer");

                            b1.Property<List<string>>("AllowedHeaders")
                                .HasColumnType("text[]");

                            b1.Property<List<string>>("AllowedMethods")
                                .HasColumnType("text[]");

                            b1.Property<List<string>>("AllowedOrigins")
                                .HasColumnType("text[]");

                            b1.Property<List<string>>("ExposeHeaders")
                                .HasColumnType("text[]");

                            b1.Property<int?>("MaxAgeSeconds")
                                .HasColumnType("integer");

                            b1.HasKey("AppId");

                            b1.ToTable("Apps");

                            b1.ToJson("CorsSettings");

                            b1.WithOwner()
                                .HasForeignKey("AppId");
                        });

                    b.Navigation("ActiveRelease");

                    b.Navigation("BuildConfigs");

                    b.Navigation("CorsSettings");

                    b.Navigation("Settings");
                });

            modelBuilder.Entity("Api.Domain.Entities.AppBuild", b =>
                {
                    b.HasOne("Api.Domain.Entities.App", "App")
                        .WithMany("AppBuilds")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("App");
                });

            modelBuilder.Entity("Api.Domain.Entities.AppBuildArtifact", b =>
                {
                    b.HasOne("Api.Domain.Entities.Artifact", "Artifact")
                        .WithMany()
                        .HasForeignKey("ArtifactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Domain.Entities.AppBuild", "BuildJob")
                        .WithMany()
                        .HasForeignKey("BuildJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artifact");

                    b.Navigation("BuildJob");
                });

            modelBuilder.Entity("Api.Domain.Entities.AppLink", b =>
                {
                    b.HasOne("Api.Domain.Entities.App", null)
                        .WithOne("Link")
                        .HasForeignKey("Api.Domain.Entities.AppLink", "AppId");

                    b.HasOne("Api.Domain.Entities.GitHubInstallation", "GitHubInstallation")
                        .WithMany("AppLinks")
                        .HasForeignKey("InstallationId");

                    b.Navigation("GitHubInstallation");
                });

            modelBuilder.Entity("Api.Domain.Entities.Artifact", b =>
                {
                    b.HasOne("Api.Domain.Entities.App", "App")
                        .WithMany("Artifacts")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Domain.Entities.AppBuild", "Build")
                        .WithMany()
                        .HasForeignKey("BuildId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("App");

                    b.Navigation("Build");
                });

            modelBuilder.Entity("Api.Domain.Entities.AuthenticationScheme", b =>
                {
                    b.HasOne("Api.Domain.Entities.App", "App")
                        .WithMany("AuthenticationSchemes")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("App");
                });

            modelBuilder.Entity("Api.Domain.Entities.DeploymentFile", b =>
                {
                    b.HasOne("Api.Domain.Entities.ObjectBlob", "Blob")
                        .WithMany("DeploymentFiles")
                        .HasForeignKey("BlobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.Domain.Entities.SpaDeployment", "Deployment")
                        .WithMany("Files")
                        .HasForeignKey("DeploymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blob");

                    b.Navigation("Deployment");
                });

            modelBuilder.Entity("Api.Domain.Entities.Log", b =>
                {
                    b.HasOne("Api.Domain.Entities.App", "App")
                        .WithMany("Logs")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Domain.Entities.Route", "Route")
                        .WithMany("Logs")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsMany("Api.Domain.Entities.FunctionLogEntry", "FunctionLogs", b1 =>
                        {
                            b1.Property<Guid>("LogId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<string>("Message")
                                .HasColumnType("text")
                                .HasAnnotation("Relational:JsonPropertyName", "message");

                            b1.Property<DateTime>("Timestamp")
                                .HasColumnType("timestamp with time zone")
                                .HasAnnotation("Relational:JsonPropertyName", "timestamp");

                            b1.Property<int>("Type")
                                .HasColumnType("integer")
                                .HasAnnotation("Relational:JsonPropertyName", "type");

                            b1.HasKey("LogId", "Id");

                            b1.ToTable("Logs");

                            b1.ToJson("FunctionLogs");

                            b1.WithOwner()
                                .HasForeignKey("LogId");
                        });

                    b.Navigation("App");

                    b.Navigation("FunctionLogs");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("Api.Domain.Entities.Release", b =>
                {
                    b.HasOne("Api.Domain.Entities.App", "App")
                        .WithMany("Releases")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Domain.Entities.SpaDeployment", "SpaDeployment")
                        .WithMany()
                        .HasForeignKey("SpaDeploymentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("App");

                    b.Navigation("SpaDeployment");
                });

            modelBuilder.Entity("Api.Domain.Entities.Route", b =>
                {
                    b.HasOne("Api.Domain.Entities.App", "App")
                        .WithMany("Routes")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Domain.Entities.RouteFolder", "Folder")
                        .WithMany("Routes")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsMany("Api.Domain.Entities.ResponseHeader", "ResponseHeaders", b1 =>
                        {
                            b1.Property<int>("RouteId")
                                .HasColumnType("integer");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<string>("Name")
                                .HasColumnType("text");

                            b1.Property<string>("Value")
                                .HasColumnType("text");

                            b1.HasKey("RouteId", "Id");

                            b1.ToTable("Routes");

                            b1.ToJson("ResponseHeaders");

                            b1.WithOwner()
                                .HasForeignKey("RouteId");
                        });

                    b.Navigation("App");

                    b.Navigation("Folder");

                    b.Navigation("ResponseHeaders");
                });

            modelBuilder.Entity("Api.Domain.Entities.RouteFolder", b =>
                {
                    b.HasOne("Api.Domain.Entities.App", "App")
                        .WithMany("RouteFolders")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Api.Domain.Entities.RouteFolder", "Parent")
                        .WithMany("SubFolders")
                        .HasForeignKey("ParentId");

                    b.Navigation("App");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Api.Domain.Entities.SpaDeployment", b =>
                {
                    b.HasOne("Api.Domain.Entities.App", "App")
                        .WithMany("SpaDeployments")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Domain.Entities.Artifact", "Artifact")
                        .WithMany("Deployments")
                        .HasForeignKey("ArtifactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.Domain.Entities.AppBuild", "Build")
                        .WithMany()
                        .HasForeignKey("BuildId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("App");

                    b.Navigation("Artifact");

                    b.Navigation("Build");
                });

            modelBuilder.Entity("Api.Domain.Entities.Variable", b =>
                {
                    b.HasOne("Api.Domain.Entities.App", "App")
                        .WithMany("Variables")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("App");
                });

            modelBuilder.Entity("Api.Domain.Entities.App", b =>
                {
                    b.Navigation("ApiKeys");

                    b.Navigation("AppBuilds");

                    b.Navigation("Artifacts");

                    b.Navigation("AuthenticationSchemes");

                    b.Navigation("Link");

                    b.Navigation("Logs");

                    b.Navigation("Releases");

                    b.Navigation("RouteFolders");

                    b.Navigation("Routes");

                    b.Navigation("SpaDeployments");

                    b.Navigation("Variables");
                });

            modelBuilder.Entity("Api.Domain.Entities.Artifact", b =>
                {
                    b.Navigation("Deployments");
                });

            modelBuilder.Entity("Api.Domain.Entities.GitHubInstallation", b =>
                {
                    b.Navigation("AppLinks");
                });

            modelBuilder.Entity("Api.Domain.Entities.ObjectBlob", b =>
                {
                    b.Navigation("DeploymentFiles");
                });

            modelBuilder.Entity("Api.Domain.Entities.Route", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("Api.Domain.Entities.RouteFolder", b =>
                {
                    b.Navigation("Routes");

                    b.Navigation("SubFolders");
                });

            modelBuilder.Entity("Api.Domain.Entities.SpaDeployment", b =>
                {
                    b.Navigation("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
