version: 2
updates:
  - package-ecosystem: "nuget"
    directories:
      - "src/services/api/Api"
      - "src/services/api/Api.Domain"
      - "src/services/api/Api.Infrastructure"
      - "src/services/api/Api.Migrations"
      - "src/services/api/Api.MigrationTest"
      - "src/services/webapp/gateway"
      - "src/services/webapp/api/functioninvoker"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directories:
      - "src/services/web"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directories:
      - "src/services/webapp/spa/worker"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
