version: 2
updates:
  - package-ecosystem: "nuget"
    directories:
      - "src/pkg/api/Api"
      - "src/pkg/api/Api.Domain"
      - "src/pkg/api/Api.Infrastructure"
      - "src/pkg/api/Api.Migrations"
      - "src/pkg/api/Api.MigrationTest"
      - "src/pkg/webapp/gateway"
      - "src/pkg/webapp/api/functioninvoker"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directories:
      - "src/pkg/web"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directories:
      - "src/pkg/webapp/spa/worker"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
