version: '3.8'
services:
  db:
    image: postgres:16.2-alpine
    container_name: mycrocloud-db
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
      
  db-migrator:
    image: mycrocloud-db-migrator
    build:
      dockerfile: WebApp.Migrations/Dockerfile
    container_name: mycrocloud-db-migrator
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Username=postgres;Password=postgres;Database=dev-mycrocloud
    depends_on:
      - db

  restapi:
    image: mycrocloud-restapi
    build:
      dockerfile: WebApp.RestApi/Dockerfile
    container_name: mycrocloud-restapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Username=postgres;Password=postgres;Database=dev-mycrocloud
    ports:
      - "5000:8080"
      
  apigateway:
    image: mycrocloud-apigateway
    build: 
      dockerfile: WebApp.MiniApiGateway/Dockerfile
    container_name: mycrocloud-apigateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Username=postgres;Password=postgres;Database=dev-mycrocloud
    ports:
      - "5001:8080"

  seq:
    image: datalust/seq
    container_name: mycrocloud-seq
    ports:
      - "8000:80"
      - "5341:5341"
    environment:
      - ACCEPT_EULA=Y
      # 7Wy6ttuopDvTau
      - SEQ_FIRSTRUN_ADMINPASSWORDHASH=QDFtcJLYGKj1Ir6xyrydGr+u6tYcTn33xd4WCe629b6cPQgPXs3UaCYyWkzJaJAyTqNgG89fdTfjF9LQYDkqvdiMsudVmoPJc1Ho3WT0j98w
    volumes:
      - seq_data:/data
    #restart: "unless-stopped"
    
volumes:
  db_data:
  seq_data: