ALTER ROLE app_migrator
  WITH LOGIN PASSWORD 'CHANGE_MIGRATOR_PW';

ALTER ROLE api_runtime
  WITH LOGIN PASSWORD 'CHANGE_API_PW';

ALTER ROLE webapp_gateway
  WITH LOGIN PASSWORD 'CHANGE_GATEWAY_PW';

ALTER ROLE grafana_reader
  WITH LOGIN PASSWORD 'CHANGE_GRAFANA_PW';
