-- Existing tables
GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA public
TO api;

GRANT USAGE, SELECT
ON ALL SEQUENCES IN SCHEMA public
TO api;

GRANT SELECT ON ALL TABLES IN SCHEMA public TO webapp_gateway;
GRANT INSERT ON TABLE public."Logs" TO webapp_gateway;

GRANT SELECT ON ALL TABLES IN SCHEMA public TO grafana;

-- Default privileges for future tables created by migrator
ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE
ON TABLES TO api;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT USAGE, SELECT
ON SEQUENCES TO api;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT ON TABLES TO webapp_gateway;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT ON TABLES TO grafana;
