services:
  api:
    image: mc-form-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=mc-form;Username=postgres;Password=postgres"
  
  db:
    image: postgres:16.2-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  
  db-migrator:
    image: mc-form-db-migrator
    build:
      context: .
      dockerfile: Migrations/Dockerfile
    depends_on:
      - db
    environment:
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=mc-form;Username=postgres;Password=postgres"