# Infrastructure services for local development
services:
  db:
    image: postgres:16.2-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  db-migrator:
    depends_on:
      - db

volumes:
  db_data:
