services:
  monitoring-alloy:
    image: grafana/alloy:latest
    command:
      - run
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.alloy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./alloy/config.alloy:/etc/alloy/config.alloy:ro
      - alloy-data:/var/lib/alloy/data
    labels:
      logging.service: monitoring-alloy
      logging.component: monitoring
    restart: unless-stopped

  monitoring-prometheus:
    image: prom/prometheus:v3.5.1
    container_name: monitoring-prometheus
    network_mode: "host"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    labels:
      logging.service: monitoring-prometheus
      logging.component: monitoring
    restart: unless-stopped

  monitoring-node-exporter:
    image: prom/node-exporter:v1.10.2
    container_name: monitoring-node-exporter
    network_mode: "host"
    labels:
      logging.service: monitoring-node-exporter
      logging.component: monitoring
    restart: unless-stopped


volumes:
  alloy-data:
  prometheus_data:
