services:
  alloy:
    image: grafana/alloy:latest
    command:
      - run
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.alloy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./alloy/config.alloy:/etc/alloy/config.alloy:ro
      - alloy-data:/var/lib/alloy/data
    labels:
      logging.service: alloy
      logging.component: monitoring
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v3.5.1
    container_name: prometheus
    network_mode: "host"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    labels:
      logging.service: prometheus
      logging.component: monitoring
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter:v1.10.2
    container_name: node-exporter
    network_mode: "host"
    labels:
      logging.service: node-exporter
      logging.component: monitoring
    restart: unless-stopped

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.52.1
    container_name: cadvisor
    network_mode: "host"
    volumes:
      - /:/rootfs:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    labels:
      logging.service: cadvisor
      logging.component: monitoring
    restart: unless-stopped


volumes:
  alloy-data:
  prometheus_data:
