{
 "title": "Logs",
 "tags": [
  "mycrocloud",
  "logs"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "service",
    "query": {}
   },
   {
    "name": "component",
    "query": {}
   },
   {
    "name": "level",
    "query": {}
   },
   { "name": "search", "label": "Search" }
  ]
 },
 "panels": [
  {
   "title": "Log Volume",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (service, level) (count_over_time({service=~\"$service\", component=~\"$component\"} |= `$search` [$__auto]))"
    }
   ]
  },
  {
   "title": "Error Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({service=~\"$service\", component=~\"$component\", level=~\"error|critical\"} [$__range]))"
    }
   ]
  },
  {
   "title": "Warn Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({service=~\"$service\", component=~\"$component\", level=\"warn\"} [$__range]))"
    }
   ]
  },
  {
   "title": "Total Logs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({service=~\"$service\", component=~\"$component\"} [$__range]))"
    }
   ]
  },
  {
   "title": "Services",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (service) (count_over_time({service=~\"$service\", component=~\"$component\"} [$__range])))"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{service=~\"$service\", component=~\"$component\"} |= `$search`"
    }
   ]
  }
 ]
}