apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-api
spec:
  stripPrefix:
    prefixes:
      - /api

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingress
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`{{ .Values.host }}`) && PathPrefix(`/api`)
      kind: Rule
      middlewares:
        - name: strip-api
      services:
        - name: {{ .Release.Name }}-api
          port: 80
    - match: Host(`{{ .Values.host }}`)
      kind: Rule
      services:
        - name: {{ .Release.Name }}-web
          port: 80