apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingress
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`{{ .Values.host }}`)
      kind: Rule
      services:
        - name: {{ .Release.Name }}-web
          port: 80