services:
  db-migrator:
    image: mycrocloud-db-migrator
    build:
      context: .
      dockerfile: Api.Migrations/Dockerfile
    volumes:
      - "./Api.Migrations/appsettings.json:/app/appsettings.json:ro"

  api:
    image: mycrocloud-api
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - "./Api/appsettings.json:/app/appsettings.json:ro"
      - "./Api/gha-mycrocloud.private-key.pem:/app/gha-mycrocloud.private-key.pem:ro"
