services:
  alloy:
    image: grafana/alloy:latest
    command:
      - run
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.alloy
    env_file:
      - ./alloy/.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./alloy/config.alloy:/etc/alloy/config.alloy:ro
      - alloy-data:/var/lib/alloy/data
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v3.5.1
    container_name: prometheus
    network_mode: "host"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    restart: unless-stopped

  node_exporter:
    image: prom/node-exporter:v1.10.2
    container_name: node_exporter
    network_mode: "host"
    restart: unless-stopped


volumes:
  alloy-data:
  prometheus_data:
