# Development environment overrides (loaded automatically)
services:
  db:
    image: postgres:16.2-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  db-migrator:
    image: mycrocloud-db-migrator
    build:
      context: ../api
      dockerfile: Api.Migrations/Dockerfile
    depends_on:
      - db

  api:
    image: mycrocloud-api
    build:
      context: ../api
      dockerfile: Api/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - "../api/Api/gha-mycrocloud.private-key.pem:/app/gha-mycrocloud.private-key.pem:ro"
    depends_on:
      rabbitmq:
        condition: service_healthy

  gateway:
    image: mycrocloud-gateway
    build:
      context: ./gateway
    volumes:
      - /tmp/function-data:/tmp/function-data
    ports:
      - "8081:8080"

  seq:
    image: datalust/seq
    ports:
      - "8000:80"
      - "5341:5341"
    environment:
      - ACCEPT_EULA=Y
      # 7Wy6ttuopDvTau
      - SEQ_FIRSTRUN_ADMINPASSWORDHASH=QDFtcJLYGKj1Ir6xyrydGr+u6tYcTn33xd4WCe629b6cPQgPXs3UaCYyWkzJaJAyTqNgG89fdTfjF9LQYDkqvdiMsudVmoPJc1Ho3WT0j98w
    volumes:
      - seq_data:/data

  redis:
    image: redis:alpine3.21
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:4.1.5-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "check_running" ]
      interval: 1s
      timeout: 2s
      retries: 5

  function-invoker:
    image: mycrocloud-function-invoker
    build:
      context: ./api/functioninvoker
    env_file:
      - .env
    volumes:
      - ./api/functioninvoker/data:/app/data
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 64M
          pids: 100
    profiles:
      - function-invoker

volumes:
  db_data:
  seq_data:
