version: '3'

services:
  db:
    image: postgres:15.2-alpine
    ports:
    - 5432:5432
    volumes:
        - postgres_data:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: YJVeuWV5Mj7eDr

  pgadmin4:
    image: dpage/pgadmin4
    ports:
        - 5050:80
    volumes:
        - pgadmin4_data:/var/lib/pgadmin
    environment:
        PGADMIN_DEFAULT_EMAIL: pvnam95@hotmail.com
        PGADMIN_DEFAULT_PASSWORD: 9xs3wVYkwSSSiG
    depends_on:
      - db

volumes:
    postgres_data:
    pgadmin4_data: