services:
  worker:
    networks:
      - default
      - webapp_default

  fluentd:
    networks:
      - default
      - webapp_default

networks:
  default:
    driver: bridge

  webapp_default:
    external: true
    name: webapp_default