name: 'Deploy'
description: 'Deploy to server via SSH'

inputs:
  # SSH Configuration
  server-host:
    description: 'Server hostname or IP'
    required: true
  ssh-private-key:
    description: 'SSH private key'
    required: true
  server-user:
    description: 'SSH user'
    default: 'ubuntu'

  # AWS Configuration
  aws-iam-role:
    description: 'AWS IAM role ARN for GitHub Actions'
    required: true
  aws-region:
    description: 'AWS region'
    required: true

  # Deploy Configuration
  image:
    description: 'Docker image to pull'
    default: ''
  pull-only:
    description: 'If true, only pull image without deploying'
    default: 'false'
  service-group:
    description: 'Service group to deploy (all, core, webapp, monitoring)'
    default: ''
  service:
    description: 'Service name to deploy in underscore format (e.g. db_migrator)'
    default: ''

runs:
  using: composite
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v5.1.1
      with:
        role-to-assume: ${{ inputs.aws-iam-role }}
        aws-region: ${{ inputs.aws-region }}

    - name: Setup SSH agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ inputs.ssh-private-key }}

    - name: Deploy
      shell: bash
      working-directory: deploy
      run: |
        pipx inject ansible-core boto3 botocore
        ansible-galaxy collection install amazon.aws community.docker
        ansible-playbook -i scripts/inventory.yml scripts/deploy.yml -e "server_host=${{ inputs.server-host }}" -e "server_user=${{ inputs.server-user }}" -e "pull_only=${{ inputs.pull-only }}" ${{ inputs.image && format('-e "image={0}"', inputs.image) || '' }} ${{ inputs.service-group && format('-e "service_group={0}"', inputs.service-group) || '' }} ${{ inputs.service && format('-e "services=[\"{0}\"]"', inputs.service) || '' }}
      env:
        AWS_REGION: ${{ inputs.aws-region }}
