name: 'Deploy'
description: 'Deploy to server via SSH - pull images and optionally deploy services'

inputs:
  # SSH Configuration
  ssh-host:
    description: 'SSH host'
    required: true
  ssh-username:
    description: 'SSH username'
    required: true
  ssh-key:
    description: 'SSH private key'
    required: true

  # AWS Configuration
  aws-iam-role:
    description: 'AWS IAM role ARN for GitHub Actions'
    required: true
  aws-region:
    description: 'AWS region'
    required: true

  # Container Registry
  gh-pat:
    description: 'GitHub Personal Access Token for container registry'
    required: true
  image:
    description: 'Docker image to pull'
    default: ''

  # Deploy Configuration
  pull-only:
    description: 'If true, only pull image without deploying'
    default: 'false'
  service-group:
    description: 'Service group to deploy (core, webapp, monitoring)'
    default: ''
  service:
    description: 'Service name to deploy (deploys all if not specified)'
    default: ''

runs:
  using: composite
  steps:
    - name: Install SSH key
      shell: bash
      run: |
        mkdir -p ~/.ssh
        echo "${{ inputs.ssh-key }}" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 400 ~/.ssh/id_rsa
        ssh-keyscan -H "${{ inputs.ssh-host }}" > ~/.ssh/known_hosts

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v5.1.1
      with:
        role-to-assume: ${{ inputs.aws-iam-role }}
        aws-region: ${{ inputs.aws-region }}

    - name: Deploy
      shell: bash
      working-directory: deploy/scripts
      run: |
        pipx inject ansible-core boto3 botocore
        ansible-galaxy collection install amazon.aws community.docker
        ansible-playbook -i inventory.yml deploy.yml -e "pull_only=${{ inputs.pull-only }}" ${{ inputs.image && format('-e "image={0}"', inputs.image) || '' }} ${{ inputs.service-group && format('-e "service_group={0}"', inputs.service-group) || '' }} ${{ inputs.service && format('-e "services=[\"{0}\"]"', inputs.service) || '' }}
      env:
        ANSIBLE_HOST: ${{ inputs.ssh-host }}
        ANSIBLE_USER: ${{ inputs.ssh-username }}
        ANSIBLE_SSH_PRIVATE_KEY_FILE: "~/.ssh/id_rsa"
        AWS_REGION: ${{ inputs.aws-region }}

    - name: Cleanup
      if: always()
      shell: bash
      run: |
        rm -r ~/.ssh
