name: CI/CD Api

on:
  push:
    branches:
      - main
    paths:
      - "services/api/Api.Domain/**"
      - "services/api/Api.Infrastructure/**"
      - "services/api/Api/**"

  workflow_dispatch:

jobs:
  build-and-deploy:
    uses: ./.github/workflows/_build-deploy.yml
    permissions:
      id-token: write
      contents: read
      packages: write
    with:
      image-name: ${{ github.repository }}-api
      work-dir: services/api
      dockerfile: Api/Dockerfile
      service: api
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
