name: Deploy ApiGateway

on:
  push:
    branches:
      - dev
    paths: 
      - 'src/Services/WebApp/WebApp.Domain/**'
      - 'src/Services/WebApp/WebApp.Infrastructure/**'
      - 'src/Services/WebApp/WebApp.MiniApiGateway/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-apigateway
  WORK_DIR: src/Services/WebApp

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.meta.outputs.tags }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{env.WORK_DIR}}
          file: ${{env.WORK_DIR}}/WebApp.MiniApiGateway/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}