name: Deploy to dev server

on:
  push:
    branches:
      - dev
    # paths:
    #   - 'src/Web/WebApp/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-webapp

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.meta.outputs.tags }}

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:src/WebApp"
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      #- run: echo "tags=${{ steps.meta.outputs.tags }}" >> "$GITHUB_OUTPUT"

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push-image

    steps:
      - name: Install ssh keys
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ vars.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to dev server
        env:
          TAG: ${{ needs.build-and-push-image.outputs.tags }}
        run: |
          echo "Deploying ${{ env.TAG }} to dev server"
          ssh ${{ vars.SSH_USERNAME }}@${{ vars.SSH_HOST }} "cd ${{ vars.WORKDIR }} && docker compose down webapp && docker compose pull webapp && docker compose up -d webapp"