name: Deploy to dev server

on:
  push:
    branches:
      - dev
    # paths:
    #   - 'src/Web/WebApp/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-webapp

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Uses the `docker/login-action` action to log in to the Container registry registry using the account and password that will publish the packages.
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: latest
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:src/Web/WebApp"
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build

  #   steps:
  #     - name: Download built artifacts
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: artifacts
  #         path: artifacts

  #     - name: Copy files to server
  #       uses: appleboy/scp-action@master
  #       with:
  #         host: ${{ vars.SSH_HOST }}
  #         username: ${{ vars.SSH_USERNAME }}
  #         key: ${{ secrets.SSH_PRIVATE_KEY }}
  #         source: artifacts/*
  #         target: /var/www/html/mycrocloud.online/
  #         strip_components: 1

  #     - name: Remove artifacts
  #       run: rm -rf artifacts
