name: CI/CD Function Invoker

on:
  push:
    branches:
      - main
    paths:
      - 'services/webapp/api/functioninvoker/**'

  workflow_dispatch:

jobs:
  build-and-deploy:
    uses: ./.github/workflows/_build-deploy.yml
    permissions:
      id-token: write
      contents: read
      packages: write
    with:
      image-name: ${{ github.repository }}-function-invoker
      work-dir: services/webapp/api/functioninvoker
      dockerfile: Dockerfile
      pull-only: true
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
