name: Publish function invoker image

on:
  push:
    branches:
      - dev

    paths:
      - 'src/Services/WebApp/WebApp.Domain/**'
      - 'src/Services/WebApp/WebApp.Infrastructure/**'
      - 'src/Services/WebApp/WebApp.FunctionShared/**'
      - 'src/Services/WebApp/WebApp.FunctionInvoker/**'

  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-function-invoker
  WORK_DIR: src/Services/WebApp

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.meta.outputs.tags }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Extract metadata (tags, labels) for Docker
        uses: docker/metadata-action@v5.5.1
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.18.0
        with:
          context: ${{env.WORK_DIR}}
          file: ${{env.WORK_DIR}}/WebApp.FunctionInvoker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            COMMIT_HASH=${{ github.sha }}