name: Publish Editor

on:
  push:
    branches:
      - dev
    paths:
      - "src/editor/**"

  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-editor
  WORK_DIR: src/editor
  VITE_PARENT_ORIGIN: https://mycrocloud.info

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.meta.outputs.tags }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "VITE_PARENT_ORIGIN=${{ env.VITE_PARENT_ORIGIN }}" > ${{env.WORK_DIR}}/.env.production
  
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.17.0
        with:
          context: ${{env.WORK_DIR}}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            COMMIT_HASH=${{ github.sha }}
          #https://docs.docker.com/build/cache/backends/gha/#using-dockerbuild-push-action
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push-image

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        uses: ./.github/actions/deploy-action
        with:
          ssh-host: ${{ vars.SSH_HOST}}
          ssh-username: ${{ vars.SSH_USERNAME }}
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          service: editor
