name: CI/CD SPA/Build Worker

on:
  push:
    branches:
      - main
    paths:
      - "services/webapp/spa/build-worker/**"

  workflow_dispatch:

jobs:
  build-and-deploy:
    uses: ./.github/workflows/_build-deploy.yml
    permissions:
      id-token: write
      contents: read
      packages: write
    with:
      image-name: ${{ github.repository }}-spa-build-worker
      work-dir: services/webapp/spa/build-worker
      dockerfile: Dockerfile
      service: webapp-spa-build-worker
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
