name: Test

on:
  workflow_dispatch:

jobs:
    main:
        runs-on: ubuntu-latest
        steps:
            - name: Debug
              run: |
                pwd
            
            - name: Checkout
              uses: actions/checkout@v4

            - name: Debug
              run: |
                pwd
                ls -la