name: Test

on:
    workflow_dispatch:

jobs:
    PrintEnvAndSecrets:
        runs-on: ubuntu-latest
        steps:
            - name: Print Environment Variables
              run: |
                print ${{ env.SSH_HOST }}
