name: CI/CD Web

on:
  push:
    branches:
      - main
    paths:
      - "services/web/**"

  workflow_dispatch:

jobs:
  build-and-deploy:
    uses: ./.github/workflows/_build-deploy.yml
    permissions:
      id-token: write
      contents: read
      packages: write
    with:
      image-name: ${{ github.repository }}-web
      work-dir: services/web
      dockerfile: Dockerfile
      service: web
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
