name: Deploy WebApp

on:
  push:
    branches:
      - dev
    paths:
      - 'src/WebApp/**'
  
  workflow_dispatch: 
    
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-webapp
  WORK_DIR: src/WebApp

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.meta.outputs.tags }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download .env file
        run: |
          curl $URL -o $DESTINATION
        env:
          URL: https://${{ secrets.CR_PAT }}@raw.githubusercontent.com/nphamvn/mycrocloud-deploy/main/dev/config/WebApp/.env
          DESTINATION: ${{env.WORK_DIR}}/.env.production

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.1.0

      - name: Build and push Docker image
        uses: docker/build-push-action@v5.3.0
        with:
          context: ${{env.WORK_DIR}}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            COMMIT_HASH=${{ github.sha }}
          #https://docs.docker.com/build/cache/backends/gha/#using-dockerbuild-push-action
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
      - name: Cleanup
        run: rm -rf ~/.ssh

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push-image

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        uses: ./.github/actions/deploy-action
        with:
          ssh-host: ${{ vars.SSH_HOST}}
          ssh-username: ${{ vars.SSH_USERNAME }}
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          service: webapp