name: Publish WebApp

on:
  push:
    branches:
      - dev
    paths:
      - "src/WebApp/**"

  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-webapp
  WORK_DIR: src/WebApp
  VITE_AUTH0_DOMAIN: https://auth.mycrocloud.info
  VITE_AUTH0_CLIENTID: 8YECKUMM3I7ejQgsVky40b5LooQB0YFf
  VITE_AUTH0_AUDIENCE: mycrocloud-api
  VITE_WEBAPP_APIGATEWAY_DOMAIN: https://apigw-__app_id__.mycrocloud.info
  VITE_GITHUB_CLIENTID: Ov23linUfO6vBqoA0S4n
  VITE_EDITOR_ORIGIN: https://editor.mycrocloud.info

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.meta.outputs.tags }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Create .env.production file
        run: |
          echo "VITE_BASE_API_URL=${{ env.VITE_BASE_API_URL }}" >> ${{env.WORK_DIR}}/.env.production
          echo "VITE_AUTH0_DOMAIN=${{ env.VITE_AUTH0_DOMAIN }}" >> ${{env.WORK_DIR}}/.env.production
          echo "VITE_AUTH0_CLIENTID=${{ env.VITE_AUTH0_CLIENTID }}" >> ${{env.WORK_DIR}}/.env.production
          echo "VITE_AUTH0_AUDIENCE=${{ env.VITE_AUTH0_AUDIENCE }}" >> ${{env.WORK_DIR}}/.env.production
          echo "VITE_WEBAPP_APIGATEWAY_DOMAIN=${{ env.VITE_WEBAPP_APIGATEWAY_DOMAIN }}" >> ${{env.WORK_DIR}}/.env.production
          echo "VITE_GITHUB_CLIENTID=${{ env.VITE_GITHUB_CLIENTID }}" >> ${{env.WORK_DIR}}/.env.production
          echo "VITE_EDITOR_ORIGIN=${{ env.VITE_EDITOR_ORIGIN }}" >> ${{env.WORK_DIR}}/.env.production

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.18.0
        with:
          context: ${{env.WORK_DIR}}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            COMMIT_HASH=${{ github.sha }}
          #https://docs.docker.com/build/cache/backends/gha/#using-dockerbuild-push-action
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push-image

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Deploy
        uses: ./.github/actions/deploy-action
        with:
          ssh-host: ${{ vars.SSH_HOST}}
          ssh-username: ${{ vars.SSH_USERNAME }}
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          service: webapp
